import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import Navigation from "@/components/organisms/header/Navigation";
import TopHeader from "@/components/organisms/top-header/TopHeader";
import Footer from "@/components/organisms/footer/Footer";
import NavSearchBar from "@/components/molecules/navbar/NavSearchBar";
import DesktopFooter from "@/components/organisms/footer/DesktopFooter";
import { CartProvider } from "@/context/CartContext";

const openSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.ttf",
  variable: "--font-open-sans",
  weight: "300 400 500 600 700 800",
});

export const metadata: Metadata = {
  title: "Furniture E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} font-opensans antialiased`}
      >
        <CartProvider>
        <TopHeader/>
        <Navigation />
        <NavSearchBar/>
        {children}
        <Footer/>
        <DesktopFooter/>
        </CartProvider>
      
      </body>
    </html>
  );
}
